-- AutoMage MVP business tables DDL
-- Database: PostgreSQL
-- Scope: org + roles + work records + artifacts + tasks + incidents + summaries + audit logs

begin;

set client_min_messages = warning;

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists organizations (
  id bigint generated by default as identity primary key,
  public_id varchar(26) not null unique,
  name varchar(128) not null,
  code varchar(64) not null unique,
  status smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  created_by bigint null,
  updated_by bigint null,
  meta jsonb not null default '{}'::jsonb
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  public_id varchar(26) not null unique,
  org_id bigint not null references organizations(id),
  username varchar(64) not null,
  password_hash varchar(255) not null,
  display_name varchar(128) not null,
  email varchar(255) null,
  status smallint not null default 1,
  last_login_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  created_by bigint null,
  updated_by bigint null,
  meta jsonb not null default '{}'::jsonb,
  constraint uq_users_org_username unique (org_id, username),
  constraint uq_users_org_email unique (org_id, email)
);

create table if not exists roles (
  id bigint generated by default as identity primary key,
  public_id varchar(26) not null unique,
  org_id bigint not null references organizations(id),
  code varchar(64) not null,
  name varchar(128) not null,
  description text null,
  status smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  created_by bigint null,
  updated_by bigint null,
  meta jsonb not null default '{}'::jsonb,
  constraint uq_roles_org_code unique (org_id, code)
);

create table if not exists user_roles (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organizations(id),
  user_id bigint not null references users(id),
  role_id bigint not null references roles(id),
  created_at timestamptz not null default now(),
  created_by bigint null,
  constraint uq_user_roles_user_role unique (user_id, role_id)
);

create table if not exists departments (
  id bigint generated by default as identity primary key,
  public_id varchar(26) not null unique,
  org_id bigint not null references organizations(id),
  parent_id bigint null references departments(id),
  name varchar(128) not null,
  code varchar(64) null,
  sort_order integer not null default 0,
  status smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  created_by bigint null,
  updated_by bigint null,
  meta jsonb not null default '{}'::jsonb,
  constraint uq_departments_org_code unique (org_id, code)
);

create table if not exists department_members (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organizations(id),
  department_id bigint not null references departments(id),
  user_id bigint not null references users(id),
  member_type smallint not null default 1,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  created_by bigint null,
  constraint uq_department_members_department_user unique (department_id, user_id)
);

create table if not exists form_templates (
  id bigint generated by default as identity primary key,
  public_id varchar(26) not null unique,
  org_id bigint not null references organizations(id),
  name varchar(128) not null,
  scope smallint not null default 1,
  status smallint not null default 1,
  schema_json jsonb not null default '{}'::jsonb,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  created_by bigint null references users(id),
  updated_by bigint null references users(id),
  meta jsonb not null default '{}'::jsonb
);

create table if not exists work_records (
  id bigint generated by default as identity primary key,
  public_id varchar(26) not null unique,
  org_id bigint not null references organizations(id),
  department_id bigint null references departments(id),
  template_id bigint not null references form_templates(id),
  user_id bigint not null references users(id),
  record_date date not null,
  title varchar(255) not null,
  status smallint not null default 0,
  submitted_at timestamptz null,
  source_type smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  created_by bigint null references users(id),
  updated_by bigint null references users(id),
  meta jsonb not null default '{}'::jsonb
);

create table if not exists work_record_items (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organizations(id),
  work_record_id bigint not null references work_records(id) on delete cascade,
  field_key varchar(128) not null,
  field_label varchar(128) not null,
  field_type varchar(32) null,
  sort_order integer not null default 0,
  value_text text null,
  value_json jsonb null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb,
  constraint uq_work_record_items_record_field unique (work_record_id, field_key)
);

create table if not exists artifacts (
  id bigint generated by default as identity primary key,
  public_id varchar(26) not null unique,
  org_id bigint not null references organizations(id),
  work_record_id bigint null references work_records(id) on delete cascade,
  task_id bigint null,
  incident_id bigint null,
  user_id bigint not null references users(id),
  artifact_type smallint not null default 1,
  title varchar(255) not null,
  storage_type smallint not null default 1,
  file_name varchar(255) null,
  file_url text null,
  mime_type varchar(128) null,
  file_size bigint null,
  status smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  created_by bigint null references users(id),
  updated_by bigint null references users(id),
  meta jsonb not null default '{}'::jsonb,
  constraint ck_artifacts_target_not_empty check (
    work_record_id is not null or task_id is not null or incident_id is not null
  )
);

create table if not exists artifact_links (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organizations(id),
  artifact_id bigint not null references artifacts(id) on delete cascade,
  link_type smallint not null default 1,
  title varchar(255) not null,
  url text not null,
  created_at timestamptz not null default now(),
  created_by bigint null references users(id)
);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  public_id varchar(26) not null unique,
  org_id bigint not null references organizations(id),
  department_id bigint null references departments(id),
  source_record_id bigint null references work_records(id),
  creator_user_id bigint not null references users(id),
  title varchar(255) not null,
  description text null,
  status smallint not null default 0,
  priority smallint not null default 2,
  due_at timestamptz null,
  started_at timestamptz null,
  closed_at timestamptz null,
  result_summary text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  created_by bigint null references users(id),
  updated_by bigint null references users(id),
  meta jsonb not null default '{}'::jsonb
);

create table if not exists task_assignments (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organizations(id),
  task_id bigint not null references tasks(id) on delete cascade,
  user_id bigint not null references users(id),
  assignment_type smallint not null default 1,
  created_at timestamptz not null default now(),
  created_by bigint null references users(id),
  constraint uq_task_assignments_task_user_type unique (task_id, user_id, assignment_type)
);

create table if not exists task_updates (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organizations(id),
  task_id bigint not null references tasks(id) on delete cascade,
  actor_user_id bigint null references users(id),
  update_type smallint not null default 1,
  content text null,
  status_before smallint null,
  status_after smallint null,
  event_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb
);

create table if not exists incidents (
  id bigint generated by default as identity primary key,
  public_id varchar(26) not null unique,
  org_id bigint not null references organizations(id),
  department_id bigint null references departments(id),
  source_record_id bigint null references work_records(id),
  related_task_id bigint null references tasks(id),
  reporter_user_id bigint not null references users(id),
  title varchar(255) not null,
  description text not null,
  severity smallint not null default 2,
  status smallint not null default 0,
  resolved_at timestamptz null,
  closed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  created_by bigint null references users(id),
  updated_by bigint null references users(id),
  meta jsonb not null default '{}'::jsonb
);

create table if not exists incident_updates (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organizations(id),
  incident_id bigint not null references incidents(id) on delete cascade,
  actor_user_id bigint null references users(id),
  update_type smallint not null default 1,
  content text null,
  status_before smallint null,
  status_after smallint null,
  event_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb
);

create table if not exists summaries (
  id bigint generated by default as identity primary key,
  public_id varchar(26) not null unique,
  org_id bigint not null references organizations(id),
  department_id bigint null references departments(id),
  user_id bigint null references users(id),
  summary_type smallint not null default 1,
  scope_type smallint not null default 1,
  summary_date date null,
  week_start date null,
  status smallint not null default 0,
  title varchar(255) null,
  content text null,
  source_count integer not null default 0,
  generated_by_type smallint not null default 2,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null,
  created_by bigint null references users(id),
  updated_by bigint null references users(id),
  meta jsonb not null default '{}'::jsonb,
  constraint ck_summaries_scope_target check (
    (scope_type = 1 and user_id is not null)
    or (scope_type = 2 and department_id is not null)
    or (scope_type = 3)
  )
);

create table if not exists summary_source_links (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organizations(id),
  summary_id bigint not null references summaries(id) on delete cascade,
  source_type smallint not null,
  source_id bigint not null,
  created_at timestamptz not null default now(),
  constraint uq_summary_source_links unique (summary_id, source_type, source_id)
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organizations(id),
  actor_user_id bigint null references users(id),
  target_type varchar(64) not null,
  target_id bigint not null,
  action varchar(128) not null,
  summary varchar(255) null,
  payload jsonb not null default '{}'::jsonb,
  event_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table artifacts
  add constraint fk_artifacts_task
  foreign key (task_id) references tasks(id);

alter table artifacts
  add constraint fk_artifacts_incident
  foreign key (incident_id) references incidents(id);

create trigger trg_organizations_set_updated_at
before update on organizations
for each row execute function set_updated_at();

create trigger trg_users_set_updated_at
before update on users
for each row execute function set_updated_at();

create trigger trg_roles_set_updated_at
before update on roles
for each row execute function set_updated_at();

create trigger trg_departments_set_updated_at
before update on departments
for each row execute function set_updated_at();

create trigger trg_form_templates_set_updated_at
before update on form_templates
for each row execute function set_updated_at();

create trigger trg_work_records_set_updated_at
before update on work_records
for each row execute function set_updated_at();

create trigger trg_work_record_items_set_updated_at
before update on work_record_items
for each row execute function set_updated_at();

create trigger trg_artifacts_set_updated_at
before update on artifacts
for each row execute function set_updated_at();

create trigger trg_tasks_set_updated_at
before update on tasks
for each row execute function set_updated_at();

create trigger trg_incidents_set_updated_at
before update on incidents
for each row execute function set_updated_at();

create trigger trg_summaries_set_updated_at
before update on summaries
for each row execute function set_updated_at();

-- Core indexes
create index if not exists idx_users_org_status_created
  on users (org_id, status, created_at desc, id desc)
  where deleted_at is null;

create index if not exists idx_user_roles_role_user
  on user_roles (role_id, user_id);

create index if not exists idx_departments_org_parent_sort
  on departments (org_id, parent_id, sort_order, id)
  where deleted_at is null;

create index if not exists idx_department_members_user_department
  on department_members (user_id, department_id);

create index if not exists idx_form_templates_org_scope_status
  on form_templates (org_id, scope, status, created_at desc, id desc)
  where deleted_at is null;

create index if not exists idx_work_records_org_status_created
  on work_records (org_id, status, created_at desc, id desc)
  where deleted_at is null;

create index if not exists idx_work_records_user_record_date
  on work_records (user_id, record_date desc, id desc)
  where deleted_at is null;

create index if not exists idx_work_records_department_record_date
  on work_records (department_id, record_date desc, id desc)
  where deleted_at is null;

create index if not exists idx_work_records_template
  on work_records (template_id);

create index if not exists idx_work_record_items_record_sort
  on work_record_items (work_record_id, sort_order, id);

create index if not exists idx_artifacts_work_record_created
  on artifacts (work_record_id, created_at desc, id desc)
  where deleted_at is null and work_record_id is not null;

create index if not exists idx_artifacts_task_created
  on artifacts (task_id, created_at desc, id desc)
  where deleted_at is null and task_id is not null;

create index if not exists idx_artifacts_incident_created
  on artifacts (incident_id, created_at desc, id desc)
  where deleted_at is null and incident_id is not null;

create index if not exists idx_artifacts_user_created
  on artifacts (user_id, created_at desc, id desc)
  where deleted_at is null;

create index if not exists idx_artifact_links_artifact
  on artifact_links (artifact_id, created_at desc, id desc);

create index if not exists idx_tasks_org_status_created
  on tasks (org_id, status, created_at desc, id desc)
  where deleted_at is null;

create index if not exists idx_tasks_department_status_due
  on tasks (department_id, status, due_at asc, id asc)
  where deleted_at is null and department_id is not null;

create index if not exists idx_tasks_creator_created
  on tasks (creator_user_id, created_at desc, id desc)
  where deleted_at is null;

create index if not exists idx_tasks_source_record
  on tasks (source_record_id)
  where source_record_id is not null;

create index if not exists idx_task_assignments_user_task
  on task_assignments (user_id, task_id);

create index if not exists idx_task_updates_task_event
  on task_updates (task_id, event_at desc, id desc);

create index if not exists idx_task_updates_org_event
  on task_updates (org_id, event_at desc, id desc);

create index if not exists idx_incidents_org_status_created
  on incidents (org_id, status, created_at desc, id desc)
  where deleted_at is null;

create index if not exists idx_incidents_department_status_created
  on incidents (department_id, status, created_at desc, id desc)
  where deleted_at is null and department_id is not null;

create index if not exists idx_incidents_reporter_created
  on incidents (reporter_user_id, created_at desc, id desc)
  where deleted_at is null;

create index if not exists idx_incidents_related_task
  on incidents (related_task_id)
  where related_task_id is not null;

create index if not exists idx_incidents_source_record
  on incidents (source_record_id)
  where source_record_id is not null;

create index if not exists idx_incident_updates_incident_event
  on incident_updates (incident_id, event_at desc, id desc);

create index if not exists idx_incident_updates_org_event
  on incident_updates (org_id, event_at desc, id desc);

create index if not exists idx_summaries_org_type_date
  on summaries (org_id, summary_type, summary_date desc, id desc)
  where deleted_at is null;

create index if not exists idx_summaries_department_type_date
  on summaries (department_id, summary_type, summary_date desc, id desc)
  where deleted_at is null and department_id is not null;

create index if not exists idx_summaries_user_type_date
  on summaries (user_id, summary_type, summary_date desc, id desc)
  where deleted_at is null and user_id is not null;

create index if not exists idx_summary_source_links_source
  on summary_source_links (source_type, source_id, summary_id);

create index if not exists idx_audit_logs_org_event
  on audit_logs (org_id, event_at desc, id desc);

create index if not exists idx_audit_logs_actor_event
  on audit_logs (actor_user_id, event_at desc, id desc)
  where actor_user_id is not null;

create index if not exists idx_audit_logs_target_event
  on audit_logs (target_type, target_id, event_at desc, id desc);

commit;
